query CurrentUser {
	currentUser {
		id
		name
		email
		permissions {
			name
		}
	}
}

mutation SignIn($email: String!, $password: String!) {
	signIn(email: $email, password: $password) {
		name
	}
}

mutation SignOut {
	signOut {
		message
	}
}

query Users {
	users {
		id
		name
		email
		permissions {
			name
		}
	}
}

mutation CreateUser($name: String!, $email: String!, $password: String!) {
	createUser(name: $name, email: $email, password: $password) {
		id
	}
}

mutation DeleteUser($id: String!) {
	deleteUser(id: $id) {
		message
	}
}

query Permissions {
	permissions {
		id
		name
	}
}

mutation AssignPermission($userId: String!, $permissionName: String!) {
	assignPermission(userId: $userId, permissionName: $permissionName) {
		message
	}
}

mutation UnassignPermission($userId: String!, $permissionName: String!) {
	unassignPermission(userId: $userId, permissionName: $permissionName) {
		message
	}
}
