query Variations {
	variations {
		id
		code
	}
}

mutation CreateVariation($code: String!) {
	createVariation(code: $code) {
		id
	}
}

mutation DeleteVariation($id: String!) {
	deleteVariation(id: $id) {
		message
	}
}
