query Variations {
	variations {
		id
		code
		variationOptions {
			id
			code
		}
	}
}

mutation CreateVariation($code: String!) {
	createVariation(code: $code) {
		id
	}
}

mutation DeleteVariation($id: String!) {
	deleteVariation(id: $id) {
		message
	}
}

mutation CreateVariationOption($code: String!, $variationId: String!) {
	createVariationOption(code: $code, variationId: $variationId) {
		id
	}
}

mutation DeleteVariationOption($id: String!) {
	deleteVariationOption(id: $id) {
		message
	}
}
